In [80]:
import numpy as np
np.set_printoptions(threshold=np.inf)
import sklearn as sk
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelBinarizer
from sklearn.preprocessing import normalize
from sklearn import preprocessing
from sklearn.compose import ColumnTransformer 
from scipy import stats
%matplotlib inline

# Importar Raw Data
El siguiente data set consiste en definir si una persona con los features (Country, Age y Salary), compra o no (Purchased) un objeto item (etiquetas)

In [81]:
# Importar Raw Data
# https://www.kaggle.com/yashsawarn/wifi-stretgth-for-rooms
# Base de datos modificados para generar Valores Faltantes
# Base de datos modificadas para generar Outliers
dataset = pd.read_csv('train-wifi stretgth for rooms.csv')
dataset = dataset.iloc[:,1::]#Remover el ID de las observaciones, informacion no relevanta
#dataset = dataset.head(n=30) #Descomentar linea si quiero los primero n elementos del dataset
print("Cantidad de elementos NaN por columna")
print(dataset.isna().sum())
print("******************************************************")
print("Visualizacion de los primeros elementos del dataset")
dataset.head(100)

Cantidad de elementos NaN por columna
Router A    10
Router B    11
Router C     8
Router D     9
Router E    10
Router F    13
Router G     8
Room ID      0
dtype: int64
******************************************************
Visualizacion de los primeros elementos del dataset


Router A  Router B  Router C  Router D  Router E  Router F  Router G  \
0      -64.0     -56.0     -61.0     -66.0     -71.0     -82.0     -81.0   
1      -68.0     -57.0     -61.0     -65.0     -71.0     -85.0     -85.0   
2      -63.0     -60.0     -60.0     -67.0     -76.0     -85.0     -84.0   
3      -61.0     -60.0     -68.0      -5.0     -77.0     -90.0     -80.0   
4      -63.0     -65.0     -60.0     -63.0     -77.0     -81.0     -87.0   
..       ...       ...       ...       ...       ...       ...       ...   
95     -74.0     -62.0     -66.0     -70.0     -76.0     -89.0     -87.0   
96     -71.0     -62.0     -63.0     -69.0     -75.0     -85.0     -87.0   
97     -71.0     -64.0     -64.0     -70.0     -78.0     -88.0     -94.0   
98     -70.0     -64.0     -66.0     -73.0     -78.0     -87.0     -94.0   
99     -72.0     -62.0     -63.0     -76.0     -81.0     -84.0     -91.0   

    Room ID  
0         1  
1         1  
2         1  
3         1  
4         1  
..      ...  
95        1  
96        1  
97        1  
98        1  
99        1  

[100 rows x 8 columns]

# Tecnica de sustitucion de valores faltantes.

In [82]:
dataset.fillna(dataset.mean(), inplace = True)
print("Cantidad de elementos NaN por columna")
print(dataset.isna().sum())
print("******************************************************")
print("Se observa que los NaN han sido eliminados")
dataset.head(n=100)



Cantidad de elementos NaN por columna
Router A    0
Router B    0
Router C    0
Router D    0
Router E    0
Router F    0
Router G    0
Room ID     0
dtype: int64
******************************************************
Se observa que los NaN han sido eliminados


Router A  Router B  Router C  Router D  Router E  Router F  Router G  \
0      -64.0     -56.0     -61.0     -66.0     -71.0     -82.0     -81.0   
1      -68.0     -57.0     -61.0     -65.0     -71.0     -85.0     -85.0   
2      -63.0     -60.0     -60.0     -67.0     -76.0     -85.0     -84.0   
3      -61.0     -60.0     -68.0      -5.0     -77.0     -90.0     -80.0   
4      -63.0     -65.0     -60.0     -63.0     -77.0     -81.0     -87.0   
..       ...       ...       ...       ...       ...       ...       ...   
95     -74.0     -62.0     -66.0     -70.0     -76.0     -89.0     -87.0   
96     -71.0     -62.0     -63.0     -69.0     -75.0     -85.0     -87.0   
97     -71.0     -64.0     -64.0     -70.0     -78.0     -88.0     -94.0   
98     -70.0     -64.0     -66.0     -73.0     -78.0     -87.0     -94.0   
99     -72.0     -62.0     -63.0     -76.0     -81.0     -84.0     -91.0   

    Room ID  
0         1  
1         1  
2         1  
3         1  
4         1  
..      ...  
95        1  
96        1  
97        1  
98        1  
99        1  

[100 rows x 8 columns]

# Tecnica de deteccion/eliminacion de outliers.

In [83]:

def removeOutlier(matrix,column):    
    print("################################################################")
    print("Evaluando valores de la columna#",column)
    columna = matrix[:,column] 
    mean = np.mean(columna, axis = 0)  
    print("Media",mean)
    sd = np.std(columna, axis = 0)
    print("Desviacion estandar",sd)
    i = 0
    itemToDelete = []
    upperLimit = mean + 3*sd
    lowerLimit = mean - 3*sd
    print("Rango de valores aceptables [",lowerLimit,",",upperLimit,"]")
    for k in columna:              
        if not (lowerLimit <= k <= upperLimit): 
            itemToDelete.append(i)            
        i = i +1
    
    print("Rows needed to be removed")
    for row in itemToDelete:       
        print("***************************************")            
        print("Outlier removido con valor",matrix[row,column]," en columna #",column)        
        print(matrix[row,:]) 
             
    matrix = np.delete(matrix,itemToDelete,0)             
    return matrix


#removeOutlier(dataset.to_numpy(),1)


datasetSinOutlier = dataset.to_numpy() 

for b in range(1,8):
    datasetSinOutlier = removeOutlier(datasetSinOutlier,b)    

print("#######################    FIN   ###################################")
print("#######################    FIN   ###################################")
print("#######################    FIN   ###################################")
print("Cantidad de outliers removidos",dataset.to_numpy().shape[0]-datasetSinOutlier.shape[0])
print("A continuacion se muestra el dataset sin outliers, descartados bajo el criterio de desviacion estandar ")
print(datasetSinOutlier)






################################################################
Evaluando valores de la columna# 1
Media -56.24647414372062
Desviacion estandar 13.103143235861502
Rango de valores aceptables [ -95.55590385130512 , -16.937044436136112 ]
Rows needed to be removed
***************************************
Outlier removido con valor -5.0  en columna # 1
[-58.  -5. -61. -66. -75. -84. -78.   1.]
***************************************
Outlier removido con valor -544.0  en columna # 1
[ -63. -544.  -53.  -65.  -52.  -92.  -89.    4.]
################################################################
Evaluando valores de la columna# 2
Media -56.34027317925241
Desviacion estandar 24.645855910286986
Rango de valores aceptables [ -130.27784091011335 , 17.597294551608556 ]
Rows needed to be removed
***************************************
Outlier removido con valor -640.0  en columna # 2
[ -66.  -62. -640.  -68.  -73.  -89.  -83.    1.]
***************************************
Outlier removido con val

# Normalizacion o estandarizacion de datos

In [84]:

min_max_scaler = preprocessing.MinMaxScaler()
X_train_minmax = min_max_scaler.fit_transform(datasetSinOutlier)
X_train_minmax
print(X_train_minmax)

[[0.14705882 0.5        0.17910448 0.18644068 0.21176471 0.4
  0.48571429 0.        ]
 [0.08823529 0.45       0.17910448 0.20338983 0.21176471 0.31428571
  0.37142857 0.        ]
 [0.16176471 0.3        0.19402985 0.16949153 0.15294118 0.31428571
  0.4        0.        ]
 [0.16176471 0.05       0.19402985 0.23728814 0.14117647 0.42857143
  0.31428571 0.        ]
 [0.13235294 0.25       0.11940299 0.16949153 0.23529412 0.25714286
  0.4        0.        ]
 [0.13235294 0.3        0.20895522 0.23728814 0.15294118 0.28571429
  0.45714286 0.        ]
 [0.10294118 0.25       0.1641791  0.16949153 0.14117647 0.37142857
  0.2        0.        ]
 [0.13235294 0.35       0.17910448 0.16949153 0.29883143 0.28571429
  0.48571429 0.        ]
 [0.16176471 0.45       0.17910448 0.20338983 0.18823529 0.34285714
  0.4        0.        ]
 [0.11764706 0.3        0.11940299 0.25423729 0.22352941 0.31428571
  0.42857143 0.        ]
 [0.19117647 0.35       0.11940299 0.39612818 0.17647059 0.2
  0.31428571 0. 