In [12]:
import numpy as np
import sklearn as sk
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelBinarizer
%matplotlib inline

# Importar Raw Data
El siguiente data set consiste en definir si una persona con los features (Country, Age y Salary), compra o no (Purchased) un objeto item (etiquetas)

In [18]:
# Importar Raw Data
dataset = pd.read_csv('Data-InvCorta-2-Steven-Jimenez.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
print("******************************")
print("Matriz de Features")
print(X)
print("******************************")
print("Vector de etiquetas")
print(y)
print("******************************")


******************************
Matriz de Features
[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]
 ['Germany' 32.0 6350.0]]
******************************
Vector de etiquetas
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes' 'Yes']
******************************


# Tecnica de sustitucion de valores faltantes.

In [19]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 58035.0]
 ['France' 35.0 58000.0]
 ['Spain' 38.1 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]
 ['Germany' 32.0 6350.0]]


# Transformacion de datos

In [15]:
# One Hot encoding para el feature Country
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 58035.0]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.1 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]
 [0.0 1.0 0.0 32.0 6350.0]]


In [20]:
# Codificar la variable dependiente o output del sistema (etiqueta)
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

[0 1 0 0 1 1 0 1 0 1 1]
